### PR TITLE
Sync versioning with decidim

### PR DESCRIPTION
**Pull request by josepjaume**
#### :tophat: What? Why?
This syncs this gem's versioning with `decidim` and sets it to the `0.9.0` branch.

#### :pushpin: Related Issues
*None*

#### :clipboard: Subtasks
*None*

### :camera: Screenshots (optional)
*None*

#### :ghost: GIF
*None*

### CODE REVIEW

**Comment by josepjaume** [comment]
@jsperezg please remember about this PR, it'd be good to merge this ASAP to prevent future blocking.

**Comment by josepjaume** [comment]
The issue here is `CircleCI`, which doesn't seem to be set up for this repo. After that, we should send a PR to `master` and make this compatible with `0.10-pre`.

**Comment by mrcasals** [comment]
@josepjaume CircleCI is failing to create the test app

**Comment by josepjaume** [comment]
@jsperezg looks like specs are failing

**Pull request closed without merging**
